Rails.application.routes.draw do
  
  # JBV 15.03.2022 - Default route / root pointed to the 'home' static page
  root to: 'static_pages#home'
  # YR 16.03.2022
  resources :items 

  # JBV 15.03.2022 - Devise autogenerated routes (sign-in, sign-up...)
  devise_for :users
  
  # JBV 15.03.2022 - Route to 'index' method of the 'items' controller created with the latter
  get 'items/index'

  # JBV 15.03.2022 - Other routes for specific static pages
  get 'static_pages/about'
  get 'static_pages/contact'

  #YR 16.03.2022 - For the show page, if we do not use resources 
  #get 'static_pages/:id'
  
  #YR 16.03.2022 - Route for the Activemailer with the Gem letterOpenerWeb
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
end
